global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'order'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'payment'
    static_configs:
      - targets: ['host.docker.internal:9091']

  - job_name: 'jaeger'
    metrics_path: /metrics
    static_configs:
      - targets: ['jaeger:16686']